# Generated by Django 5.2.7 on 2025-10-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficdata',
            name='lane_type',
            field=models.CharField(choices=[('straight', 'Straight'), ('left', 'Left Turn'), ('right', 'Right Turn')], default='straight', max_length=10),
        ),
    ]
