# Generated by Django 5.2.7 on 2025-11-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_mltraininglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='mltraininglog',
            name='mode',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='signalcycle',
            name='mode',
            field=models.CharField(default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='trafficdata',
            name='mode',
            field=models.CharField(choices=[('normal', 'Normal'), ('peak', 'Peak')], default='normal', help_text='Indicates whether this data is from normal or peak mode', max_length=10),
        ),
    ]
